import React from 'react';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import SideBar from '../components/SideBar';
export default function Welcome() {
  const user = useAppSelector((state) => state.user);
  return (
    <section className="container">
      <div className="row">
        {user.firstName ? (
          <h1>Hello {user.firstName}</h1>
        ) : (
          <h1>Welcome to the Shelter finding tool</h1>
        )}
      </div>
      <div className="row">
        <section className="col-8">
          <h2>About this tool</h2>
          <p>
            This Shelter finding tool provides information about shelters within
            the USA. Information regarding shelters are provided by users and
            shelter owners. In the navigation menu you will be able to find a
            like to "Shelters" that will lead to all the shelters found in our
            database.
          </p>
          <h2>Contributing</h2>
          <p>
            If you would like to contribute information regarding a shelter or
            update information regarging a shelter, please register an account.
            Because information on this site is generated by users and staff
            from the shelter, information here can be updated as soon as the
            staff is able to provide information to the database.
          </p>
        </section>
        <SideBar />
      </div>
    </section>
  );
}
